name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest # Change the OS to Windows

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Update to the latest version of actions/checkout

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.2' # Update to the desired Go version compatible with Windows

    - name: Build
      run: |
        cd cmd
        go build .

    - name: Test
      run: go test .
